---
project: CMP_SEs
kind: PIPELINE
name: Template_name
icon: organization,left, is-teal
enabled: true
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: SSH
        input:
          script: |2


            toto="Hello $NAME"
            echo $toto
          username: root
          password: ${var.LinuxPassword}
          passphrase: ''
          privatekey: ''
          host: ${var.Alex_IP_server_scripts_SSH}
          workingDirectory: ''
          arguments: [
            ]
          environmentVariables:
            NAME: Alex
